<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE commandindex
[
   <!ELEMENT commandindex (entry+)>
   <!ELEMENT entry (name,category,parameters*,description+,reference*,related*,example*)>
   <!ATTLIST entry type (command | variable | keyword | option | constant | operator) #REQUIRED>
   <!ELEMENT name (#PCDATA)>
   <!ELEMENT category (#PCDATA)>
   <!ELEMENT parameters ANY>
   <!ATTLIST parameters ret CDATA #IMPLIED>
   <!ELEMENT description ANY>
   <!ELEMENT reference ANY>
   <!ATTLIST description lang CDATA #REQUIRED>
   <!ELEMENT related (#PCDATA)>
   <!ELEMENT example (#PCDATA)>
   <!ELEMENT obj (#PCDATA)>
   <!ELEMENT cmd (#PCDATA)>
   <!ELEMENT char (#PCDATA)>
   <!ELEMENT file (#PCDATA)>
   <!ELEMENT func (#PCDATA)>
   <!ATTLIST func optional (true | false) "false">
   <!ELEMENT strng (#PCDATA)>
   <!ATTLIST strng optional (true | false) "false">
   <!ELEMENT bool (#PCDATA)>
   <!ATTLIST bool optional (true | false) "false">
   <!ELEMENT table (#PCDATA)>
   <!ELEMENT mtrx (#PCDATA)>
   <!ATTLIST mtrx elem CDATA #IMPLIED>
   <!ATTLIST mtrx optional (true | false) "false">
   <!ELEMENT expr (#PCDATA)>
   <!ATTLIST expr optional (true | false) "false">
   <!ELEMENT var (#PCDATA)>
   <!ATTLIST var optional (true | false) "false">
   <!ELEMENT quoted ANY>
   <!ATTLIST quoted elem CDATA #IMPLIED>
   <!ATTLIST quoted optional (true | false) "false">
   <!ELEMENT interval ANY>
   <!ATTLIST interval optional (true | false) "false">
   <!ELEMENT real (#PCDATA)>
   <!ATTLIST real optional (true | false) "false">
   <!ELEMENT intg (#PCDATA)>
   <!ATTLIST intg optional (true | false) "false">
   <!ATTLIST intg dom CDATA #IMPLIED>
   <!ELEMENT cycle (#PCDATA)>
   <!ELEMENT permut (#PCDATA)>
   <!ELEMENT unit (#PCDATA)>
   <!ELEMENT cplx (#PCDATA)>
   <!ATTLIST cplx optional (true | false) "false">
   <!ELEMENT poly (#PCDATA)>
   <!ELEMENT pnt (#PCDATA)>
   <!ATTLIST pnt optional (true | false) "false">
   <!ELEMENT line (#PCDATA)>
   <!ATTLIST line optional (true | false) "false">
   <!ELEMENT plane (#PCDATA)>
   <!ELEMENT circle (#PCDATA)>
   <!ELEMENT segment (#PCDATA)>
   <!ELEMENT geo (#PCDATA)>
   <!ATTLIST geo dim (2 | 3) #IMPLIED>
   <!ATTLIST geo optional (true | false) "false">
   <!ELEMENT option (#PCDATA)>
   <!ATTLIST option optional (true | false) "false">
   <!ELEMENT equal ANY>
   <!ATTLIST equal optionalrhs (true | false) "false">
   <!ATTLIST equal optionallhs (true | false) "false">
   <!ATTLIST equal optional (true | false) "false">
   <!ELEMENT seq ANY>
   <!ATTLIST seq elem CDATA #IMPLIED>
   <!ATTLIST seq explicit (true | false) "false">
   <!ATTLIST seq optional (true | false) "false">
   <!ATTLIST seq alt CDATA #IMPLIED>
   <!ELEMENT lst ANY>
   <!ATTLIST lst elem CDATA #IMPLIED>
   <!ATTLIST lst explicit (true | false) "false">
   <!ATTLIST lst optional (true | false) "false">
   <!ATTLIST lst alt CDATA #IMPLIED>
   <!ELEMENT vect (#PCDATA)>
   <!ATTLIST vect elem CDATA #IMPLIED>
   <!ATTLIST vect optional (true | false) "false">
   <!ELEMENT set ANY>
   <!ATTLIST set elem CDATA #IMPLIED>
   <!ELEMENT or ANY>
   <!ATTLIST or name CDATA #IMPLIED>
   <!ATTLIST or alt CDATA #IMPLIED>
   <!ATTLIST or optional (true | false) "false">
   <!ELEMENT el ANY>
   <!ELEMENT etc EMPTY>
   <!ELEMENT null EMPTY>
   <!ELEMENT zero EMPTY>
   <!ELEMENT i ANY>
   <!ELEMENT b ANY>
   <!ELEMENT tt (#PCDATA)>
   <!ELEMENT a (#PCDATA)>
   <!ATTLIST a href CDATA #REQUIRED>
   <!ELEMENT sup ANY>
   <!ELEMENT sub ANY>
   <!ELEMENT radicand ANY>
   <!ENTITY sdot "·">
   <!ENTITY sum "∑">
   <!ENTITY infin "∞">
   <!ENTITY sup1 "¹">
   <!ENTITY sup2 "²">
   <!ENTITY sup3 "³">
   <!ENTITY minus "−">
   <!ENTITY hellip "…">
   <!ENTITY le "≤">
   <!ENTITY ge "≥">
   <!ENTITY times "×">
   <!ENTITY isin "∈">
   <!ENTITY equiv "≡">
   <!ENTITY notin "∉">
   <!ENTITY ne "≠">
   <!ENTITY rarr "→">
   <!ENTITY radic "√">
   <!ENTITY int "∫">
   <!ENTITY sim "∼">
   <!ENTITY prime "′">
   <!ENTITY ang "∠">
   <!ENTITY Prime "″">
   <!ENTITY plusmn "±">
   <!ENTITY nabla "∇">
   <!ENTITY part "∂">
   <!ENTITY cup "∪">
   <!ENTITY cap "∩">
]>

<commandindex>
  <entry type="command">
    <name>smith</name>
    <category>Algebra:Linear</category>
    <parameters ret="seq(mtrx)"><mtrx>A</mtrx></parameters>
    <description lang="en">Smith normal form of a matrix with polynomial coefficients: returns matrices <b>U</b>,<b>D</b>,<b>V</b> such that <b>U</b> and <b>V</b> are invertible, <b>D</b> is diagonal, and <b>U</b>&sdot;<b>A</b>&sdot;<b>V</b>=<b>D</b>.</description>
    <description lang="fr">Calcule la forme normale de Smith d'une matrice a coefficients polynomiaux : renvoie <b>U</b>,<b>D</b>,<b>V</b> tels que tels que <b>U</b> et <b>V</b> inversibles, <b>D</b> diagonale et <b>U</b>&sdot;<b>A</b>&sdot;<b>V</b>=<b>D</b>.</description>
    <description lang="de">Gibt die Smith-Normalform der Koeffizientenmatrix an (<b>U</b>,<b>D</b>,<b>V</b> wobei <b>U</b>&sdot;<b>A</b>&sdot;<b>V</b>=<b>D</b>)</description>
    <description lang="es">Calcula la forma normal de Smith de una matriz a coeficientes polinomiales: devuelve <b>U</b>,<b>D</b>,<b>V</b> tales que <b>U</b> y <b>V</b> invertibles, <b>D</b> diagonal, y <b>U</b>&sdot;<b>A</b>&sdot;<b>V</b>=<b>D</b>.</description>
    <description lang="el">Υπολογίζει την κανονική μορφή Smith ενός πίνακα με συντελεστές πολυώνυμα : επιστρέφει <b>U</b>,<b>D</b>,<b>V</b> τέτοια ώστε <b>U</b> και <b>V</b> αντιστρέψιμα, <b>D</b> διαγώνιος, και <b>U</b>&sdot;<b>A</b>&sdot;<b>V</b>=<b>D</b>.</description>
    <description lang="zh"></description>
    <description lang="hr">Matrice <b>U</b>, <b>D</b> i <b>V</b> takve da su <b>U</b> i <b>V</b> invertibilne, <b>D</b> dijagonalna te vrijedi <b>U</b>&sdot;<b>A</b>&sdot;<b>V</b>=<b>D</b> (Smithova normalna forma).</description>
    <reference><a href="https://www.encyclopediaofmath.org/index.php/Normal_form_(for_matrices)#The_Smith_normal_form.">The Smith normal form</a>. <i>Encyclopedia of Mathematics</i>.</reference>
    <related>hermite</related>
    <related>ismith</related>
    <related>ihermite</related>
    <example>n:=10; A:=ranm(n,n) % 17; U,D,V:=smith(x*idn(n)-A);normal(U*(x*idn(n)-A)*V-D); diag(D);</example>
    <example>GF(3,5,g); n:=3; A:=ranm(n,n,g); U,D,V:=smith(x*idn(n)-A);normal(U*(x*idn(n)-A)*V-D); diag(D);</example>
  </entry>
  <entry type="command">
    <name>wz_certificate</name>
    <category>Combinatorics</category>
    <parameters ret="expr">
      <expr>f(n, k)</expr>
      <expr>r</expr>
      <var>n</var>
      <var>k</var>
    </parameters>
    <description lang="en">Wilf-Zeilberger certificate for an identity <b>&sum;</b><sub>k</sub><i>U</i>(<i>n</i>,<i>k</i>) = <i>r</i>.</description>
    <description lang="fr">Certificat de Wilf-Zeilberger pour une identite <b>&sum;</b><sub>k</sub><i>U</i>(<i>n</i>,<i>k</i>) = <i>r</i>.</description>
    <description lang="de">Wilf-Zeilberger Zertifikat</description>
    <description lang="es"></description>
    <description lang="el"></description>
    <description lang="zh"></description>
    <description lang="hr">Wilf-Zeilbergerov certifikat za identitet <b>&sum;</b><sub>k</sub><i>U</i>(<i>n</i>,<i>k</i>) = <i>r</i>.</description>
    <reference><a href="https://en.wikipedia.org/wiki/Wilf%E2%80%93Zeilberger_pair">Wilf–Zeilberger pair</a>. <i>Wikipedia</i>, the free encyclopedia.</reference>
    <related>sum</related>
    <example>wz_certificate((-1)^k*comb(n,k)*comb(2k,k)*4^(n-k),comb(2n,n),n,k);</example>
    <example>wz_certificate((-1)^k*comb(n,k)/comb(k+a,k),a/(n+a),n,k);</example>
    <example>wz_certificate((-1)^(n-k)*comb(2n,k)^2,comb(2n,n),n,k);</example>
    <example>wz_certificate((a+k)!*(b+k)!*(c+n-k-a-b-1)!/(k+1)!/(n-k)!/(c+k)!,(a-1)!*(b-1)!*(c-a-b-1)!*(c+n-a)!*(c+n-b)!/(c-a-1)!/(c-b-1)!/(n+1)!/(c+n)!,n,k);</example>
  </entry>
  <entry type="variable">
    <name>keep_algext</name>
    <category>General:Session</category>
    <description lang="en">Pseudo-variable to keep algebraic extensions (<tt>keep_algext:=1</tt>) or try to rewrite them (<tt>keep_algext:=0</tt>).</description>
    <description lang="fr">Laisse les extensions algébriques telles quelles (<tt>keep_algext:=1</tt>) ou tente de les réécrire (<tt>keep_algext:=0</tt>).</description>
    <description lang="de">Pseudevariable, die benutzt werden kann um algebraische Erweiterungen zu behalten (<tt>keep_algext:=1</tt>) oder um sie zu überschreiben (<tt>keep_algext:=0</tt>).</description>
    <description lang="es"></description>
    <description lang="el"></description>
    <description lang="zh"></description>
    <description lang="hr">Pseudo-varijabla, za <tt>keep_algext:=1</tt> algebarska proširenja se ne raspisuju, a za <tt>keep_algext:=0</tt> se automatski raspisuju.</description>
    <example>keep_algext:=1</example>
  </entry>
  <entry type="command">
    <name>jacobi_linsolve</name>
    <category>Algebra:Linear</category>
    <parameters ret="vect">
      <mtrx>A</mtrx>
      <vect>b</vect>
      <real>ε</real>
      <intg optional="true"></intg>
    </parameters>
    <description lang="en">Resolution of a linear system <b>A</b>&sdot;<b>x</b> = <b>b</b> by the iterative Jacobi method with <i>ε</i> as error margin and a number of iterations inferior to <i>n</i>.</description>
    <description lang="fr">Résolution d'un système linéaire de matrice <b>A</b> et de second membre <b>b</b>, par la méthode itérative de Jacobi avec une tolérance de <i>ε</i> et un nombre maximal d'itérations de <i>n</i>. </description>
    <description lang="de">Loesung eines linearen Gleichungssystems <b>A</b>&sdot;<b>x</b> = <b>b</b> mit dem Jacobi-Verfahren. Die Groesse des Fehlers wird mit <i>ε</i> festgelegt und die die maximale Anzahl der Iterationen mit <i>n</i>.</description>
    <description lang="es"></description>
    <description lang="el"></description>
    <description lang="zh"></description>
    <description lang="hr">Rješenje sustava linearnih jednadžbi <b>A</b>&sdot;<b>x</b> = <b>b</b> dobivenog Jacobijevom metodom s najvećom dopustivom greškom <i>ε</i> i brojem iteracija ne većim od <i>n</i>.</description>
    <related>gauss_seidel_linsolve</related>
    <related>linsolve</related>
    <example>a:=[[100,2],[2,100]];jacobi_linsolve(a,[0,1],1e-12);</example>
    <example>a:=[[100,2],[2,100]];jacobi_linsolve(table(a),[0,1],1e-12); </example>
  </entry>
  <entry type="command">
    <name>gauss_seidel_linsolve</name>
    <category>Algebra:Linear</category>
    <parameters ret="vect">
      <real optional="true">ω</real>
      <mtrx>A</mtrx>
      <vect>b</vect>
      <real>ε</real>
      <intg optional="true">n</intg>
    </parameters>
    <description lang="en">Resolution of a linear system <b>A</b>&sdot;<b>x</b>=<b>b</b> by the iterative Gauss-Seidel method (by defaut <i>ω</i> = 1) or by relaxation method, with <i>ε</i> as error margin and a number of iterations inferior to <i>n</i>.</description>
    <description lang="fr">Résolution d'un système linéaire de matrice <b>A</b> et de second membre <b>b</b>, par la méthode itérative de Gauss-Seidel (par défaut <i>ω</i> = 1) ou de relaxation avec une tolérance de <i>ε</i> et un nombre maximal d'itérations de <i>n</i>.</description>
    <description lang="de">Loesung eines linearen Gleichungssystems <b>A</b>&sdot;<b>x</b>=<b>b</b> mit dem Gauss-Seidel-Verfahren (ohne Spezifikation <i>ω</i> = 1) oder dem Relaxationsverfahren, wobei die Groesse des Fehlers mit <i>ε</i> und die die maximale Anzahl der Iterationen mit <i>n</i> festgelegt wird.</description>
    <description lang="es"></description>
    <description lang="el"></description>
    <description lang="zh"></description>
    <description lang="hr">Rješenje sustava linearnih jednadžbi <b>A</b>&sdot;<b>x</b>=<b>b</b> dobivenog Gauss-Seidelovom metodom (s zadanom vrijednosti <i>ω</i> = 1) ili metodom relaksacije, s najvećom dopustivom greškom <i>ε</i> i brojem iteracija ne većim od <i>n</i>.</description>
    <reference><a href="http://www.encyclopediaofmath.org/index.php?title=Seidel_method">Seidel method</a>. <i>Encyclopedia of Mathematics</i>.</reference>
    <related>jacobi_linsolve</related>
    <related>linsolve</related>
    <example>a:=[[100,2],[2,100]];gauss_seidel_linsolve(a,[0,1],1e-12);</example>
    <example>a:=[[100,2],[2,100]];gauss_seidel_linsolve(table(a),[0,1],1e-12); </example>
    <example>a:=[[100,2],[2,100]];gauss_seidel_linsolve(1.5,a,[0,1],1e-12);</example>
    <example>a:=[[100,2],[2,100]];gauss_seidel_linsolve(1.5,table(a),[0,1],1e-12); </example>
  </entry>
  <entry type="command">
    <name>linspace</name>
    <category>Algebra:Linear</category>
    <parameters ret="lst">
      <real>a</real>
      <real>b</real>
      <intg optional="true">n</intg>
    </parameters>
    <description lang="en">Creates a list of <i>n</i> elements at regular intervals between <i>a</i> and <i>b</i>, by defaut <i>n</i>=100 (compatibility with Scilab).</description>
    <description lang="fr">Génère une liste de <i>n</i> éléments régulièrement espacés entre <i>a</i> et <i>b</i>, par défaut <i>n</i>=100 (commande compatible Scilab).</description>
    <description lang="de">Generiert eine Liste aus <i>n</i> aequidistanten Elementen zwischen <i>a</i> und <i>b</i>, ohne Spezifikation <i>n</i>=100 (kompatibel mit Scilab).</description>
    <description lang="es"></description>
    <description lang="el"></description>
    <description lang="zh"></description>
    <description lang="hr">Lista <i>n</i> ekvidistantnih čvorova između <i>a</i> i <i>b</i> sa zadanom vrijednosti <i>n</i>=100 (kompatibilnost s paketom Scilab).</description>
    <example>linspace(0,1,11)</example>
  </entry>
  <entry type="command">
    <name>besselY</name>
    <category>Functions:Special</category>
    <parameters ret="real">
      <real>x</real>
      <intg>p</intg>
    </parameters>
    <description lang="en">Returns the value of the Bessel function of the second kind <i>Y</i><sub>p</sub>(<i>x</i>).</description>
    <description lang="fr">Renvoie la valeur de la fonction de Bessel de deuxième espèce <i>Y</i><sub>p</sub>(<i>x</i>).</description>
    <description lang="de"></description>
    <description lang="es"></description>
    <description lang="el"></description>
    <description lang="zh"></description>
    <description lang="hr">Vrijednost Besselove funkcije druge vrste <i>Y</i><sub>p</sub>(<i>x</i>).</description>
    <reference><a href="http://www.encyclopediaofmath.org/index.php?title=Bessel_function_of_the_second_kind">Neumann function</a>. <i>Encyclopedia of Mathematics</i>.</reference>
    <related>BesselY</related>
    <related>BesselJ</related>
    <related>besselJ</related>
    <example>besselY(sqrt(2),2)</example>
    <example>besselY(sqrt(2),-2)</example>
  </entry>
  <entry type="command">
    <name>BesselY</name>
    <category>Functions:Special</category>
    <parameters ret="real">
      <intg>p</intg>
      <real>x</real>
    </parameters>
    <description lang="en">Returns the value of the Bessel function of the second kind <i>Y</i><sub>p</sub>(<i>x</i>).</description>
    <description lang="fr">Renvoie la valeur de la fonction de Bessel de deuxième espèce <i>Y</i><sub>p</sub>(<i>x</i>).</description>
    <description lang="de"></description>
    <description lang="es"></description>
    <description lang="el"></description>
    <description lang="zh"></description>
    <description lang="hr">Vrijednost Besselove funkcije druge vrste <i>Y</i><sub>p</sub>(<i>x</i>).</description>
    <reference><a href="http://www.encyclopediaofmath.org/index.php?title=Bessel_function_of_the_second_kind">Neumann function</a>. <i>Encyclopedia of Mathematics</i>.</reference>
    <related>besselY</related>
    <related>BesselJ</related>
    <related>besselJ</related>
    <example>BesselJ(2,sqrt(2))</example>
    <example>BesselJ(-2,sqrt(2))</example>
  </entry>
  <entry type="command">
    <name>besselJ</name>
    <category>Functions:Special</category>
    <parameters ret="real">
      <real>x</real>
      <intg>p</intg>
    </parameters>
    <description lang="en">Returns the value of the Bessel function of the first kind <i>J</i><sub>p</sub>(<i>x</i>).</description>
    <description lang="fr">Renvoie la valeur de la fonction de Bessel de première espèce <i>J</i><sub>p</sub>(<i>x</i>).</description>
    <description lang="de"></description>
    <description lang="es"></description>
    <description lang="el"></description>
    <description lang="zh"></description>
    <description lang="hr">Vrijednost Besselove funkcije prve vrste <i>J</i><sub>p</sub>(<i>x</i>).</description>
    <reference><a href="http://www.encyclopediaofmath.org/index.php?title=Bessel_functions">Bessel functions</a>. <i>Encyclopedia of Mathematics</i>.</reference>
    <related>BesselJ</related>
    <related>BesselY</related>
    <related>besselY</related>
    <example>besselJ(sqrt(2),2)</example>
    <example>besselJ(sqrt(2),-2)</example>
  </entry>
  <entry type="command">
    <name>BesselJ</name>
    <category>Functions:Special</category>
    <parameters ret="real">
      <intg>p</intg>
      <real>x</real>
    </parameters>
    <description lang="en">Returns the value of the Bessel function of the first kind <i>J</i><sub>p</sub>(<i>x</i>).</description>
    <description lang="fr">Renvoie la valeur de la fonction de Bessel de première espèce <i>J</i><sub>p</sub>(<i>x</i>).</description>
    <description lang="de"></description>
    <description lang="es"></description>
    <description lang="el"></description>
    <description lang="zh"></description>
    <description lang="hr">Vrijednost Besselove funkcije prve vrste <i>J</i><sub>p</sub>(<i>x</i>).</description>
    <reference><a href="http://www.encyclopediaofmath.org/index.php?title=Bessel_functions">Bessel functions</a>. <i>Encyclopedia of Mathematics</i>.</reference>
    <related>besselJ</related>
    <related>BesselY</related>
    <related>besselY</related>
    <example>BesselJ(2,sqrt(2))</example>
    <example>BesselJ(-2,sqrt(2))</example>
  </entry>
  <entry type="command">
    <name>batons</name>
    <category>Plotting</category>
    <parameters ret="geo2"><mtrx/></parameters>
    <description lang="en">Draws the segments from (<i>x</i><sub><i>k</i></sub>,0) to (<i>x</i><sub><i>k</i></sub>,<i>y</i><sub><i>k</i></sub>) for <i>k</i>=0‥<tt>nrows</tt>, where <i>x</i><sub><i>k</i></sub> is the <i>k</i>-th element of the zeroth column and <i>y</i><sub><i>k</i></sub> is the <i>k</i>-th element of the <i>j</i>-th column (<i>j</i>=1‥<tt>ncols</tt>).</description>
    <description lang="fr">Dessine pour <i>k</i>=0‥<tt>nrows</tt>, les segments (<i>x</i><sub><i>k</i></sub>,0)-(<i>x</i><sub><i>k</i></sub>,<i>y</i><sub><i>k</i></sub>) où <i>x</i><sub><i>k</i></sub>=élément ligne <i>k</i> colonne 0 et <i>y</i><sub><i>k</i></sub>=élément ligne <i>k</i> colonne <i>j</i> (<i>j</i>=1‥<tt>ncols</tt>).</description>
    <description lang="de"></description>
    <description lang="es"></description>
    <description lang="el"></description>
    <description lang="zh"></description>
    <description lang="hr">Prikaz spojnica (<i>x</i><sub><i>k</i></sub>,0)-(<i>x</i><sub><i>k</i></sub>,<i>y</i><sub><i>k</i></sub>) za <i>k</i>=0‥<tt>nrows</tt>, gdje je <i>x</i><sub><i>k</i></sub> <i>k</i>-ti element nultog stupca, a <i>y</i><sub><i>k</i></sub> <i>k</i>-ti element <i>j</i>-tog stupca dane matrice (<i>j</i>=1‥<tt>ncols</tt>).</description>
    <related>polygonplot</related>
    <related>scatterplot</related>
    <related>listplot</related>
    <example>batons([1,3],[2,5],[3,2])</example>
    <example>batons([[1,3],[2,5],[3,2]])</example>
    <example>batons([1,2,3],[3,5,2])</example>
  </entry>
  <entry type="operator">
    <name>()</name>
    <category>General</category>
    <description lang="en">() returns the value of a function or substitutes values in an expression.</description>
    <description lang="fr">() renvoie la valeur d'une fonction ou permet de substituer des valeurs dans une expression.</description>
    <description lang="de"></description>
    <description lang="es"></description>
    <description lang="el"></description>
    <description lang="zh"></description>
    <description lang="hr">Izračun vrijednosti dane funkcije ili uvrštavanje vrijednosti određenih parametara u danom izrazu.</description>
    <related>subst</related>
    <related>-&gt;</related>
    <related>:=</related>
    <example>f(x,y,z):=x+2y+3z;f(1,2,z)</example>
    <example>f:=(x,y,z)-&gt;x+2y+3z;f(1,2,z)</example>
    <example>g:=x+2y+3z;g(x=1,y=2)</example>
  </entry>
  <entry type="command">
    <name>REDIM redim</name>
    <category>Algebra:Linear</category>
    <parameters ret="mtrx||vect">
      <or><mtrx/><vect/></or>
      <intg>m</intg>
      <intg>n</intg>
    </parameters>
    <description lang="en">Shrink or enlarge with 0 a matrix (or vector) according to the new dimensions <i>m</i> and <i>n</i>.</description>
    <description lang="fr">Redimensionne selon <i>m</i>, <i>n</i> une matrice (resp. vecteur) soit en la raccourcissant, soit en l'augmentant avec des 0.</description>
    <description lang="de"></description>
    <description lang="es"></description>
    <description lang="el"></description>
    <description lang="zh"></description>
    <description lang="hr">Nadopunjava matricu ili vektor nulama s obzirom na nove dimenzije <i>m</i> i <i>n</i>.</description>
    <related>replace</related>
    <example>redim([[1,2,3],[3,-9,6],[4,5,6]],1,2)</example>
    <example>redim([[1,2,3],[3,-9,6],[4,5,6]],4,4)</example>
  </entry>
  <entry type="command">
    <name>REPLACE replace</name>
    <category>Algebra:Linear</category>
    <parameters ret="mtrx">
      <mtrx>A</mtrx>
      <lst elem="intg" explicit="true"><el>n1</el><el>n2</el></lst>
      <mtrx>B</mtrx>
    </parameters>
    <description lang="en">Replace part of matrix <b>A</b> from indices <i>n</i><sub>1</sub>, <i>n</i><sub>2</sub> with the values of matrix <b>B</b>.</description>
    <description lang="fr">La matrice <b>B</b> est mise en remplacement dans <b>A</b> à partir des 2 indices <i>n</i><sub>1</sub>, <i>n</i><sub>2</sub>.</description>
    <description lang="de"></description>
    <description lang="es"></description>
    <description lang="el"></description>
    <description lang="zh"></description>
    <description lang="hr">Zamjenjuje dio matrice <b>A</b> od indeksa <i>n</i><sub>1</sub>, <i>n</i><sub>2</sub> vrijednostima iz matrice <b>B</b>.</description>
    <related>redim</related>
    <example>replace([[1,2,3],[3,-9,6],[4,5,6]],[1,0],[[7,8],[9,0]])</example>
  </entry>
  <entry type="command">
    <name>infnorm</name>
    <category>Algebra:Linear</category>
    <parameters ret="real"><mtrx/></parameters>
    <description lang="en">Matrix norm induced by <i>l</i><sub>&infin;</sub> norm.</description>
    <description lang="fr">Triple norme d'une matrice subordonnée soit à la norme <i>l</i><sub>&infin;</sub>.</description>
    <description lang="de"></description>
    <description lang="es"></description>
    <description lang="el"></description>
    <description lang="zh"></description>
    <description lang="hr">Izračunava <i>l</i><sub>&infin;</sub>-normu matrice.</description>
    <reference><a href="http://www.encyclopediaofmath.org/index.php?title=Norm">Norm</a>. <i>Encyclopedia of Mathematics</i>.</reference>
    <related>l1norm</related>
    <related>l2norm</related>
    <related>matrix_norm</related>
    <related>frobenius_norm</related>
    <example>infnorm([[1,2,3],[3,-9,6],[4,5,6]])</example>
  </entry>
  <entry type="command">
    <name>frobenius_norm</name>
    <category>Algebra:Linear</category>
    <parameters ret="real"><mtrx>A</mtrx></parameters>
    <description lang="en">Frobenius norm (<b>&sum;</b>∣<i>a</i><sub><i>ij</i></sub>∣&sup2;)<sup>&minus;1/2</sup> of the matrix <b>A</b>.</description>
    <description lang="fr">Norme de Frobenius(<b>&sum;</b>∣<i>a</i><sub><i>ij</i></sub>∣&sup2;)<sup>&minus;1/2</sup> d'une matrice <b>A</b>.</description>
    <description lang="de"></description>
    <description lang="es"></description>
    <description lang="el"></description>
    <description lang="zh"></description>
    <description lang="hr">Frobeniusova norma (<b>&sum;</b>∣<i>a</i><sub><i>ij</i></sub>∣&sup2;)<sup>&minus;1/2</sup> matrice <b>A</b>.</description>
    <reference><a href="http://www.encyclopediaofmath.org/index.php?title=Frobenius_matrix_norm">Frobenius matrix norm</a>. <i>Encyclopedia of Mathematics</i>.</reference>
    <related>l1norm</related>
    <related>l2 norm</related>
    <related>linfnorm</related>
    <related>matrix_norm</related>
    <example>frobenius_norm([[1,2,3],[3,-9,6],[4,5,6]])</example>
  </entry>
  <entry type="command">
    <name>matrix_norm</name>
    <category>Algebra:Linear</category>
    <parameters ret="real">
      <mtrx/>
      <expr optional="true">t</expr>
    </parameters>
    <description lang="en">Matrix norm induced by <i>l</i><sub>1</sub> (if <i>t</i> = 1, the default) or by <i>l</i><sub>2</sub> (if <i>t</i> = 2) or by <i>l</i><sub>&infin;</sub> norm (if <i>t</i> = <tt>inf</tt>).</description>
    <description lang="fr">Triple norme d'une matrice subordonnée soit à la norme <i>l</i><sub>1</sub> (si <i>t</i> = 1, le défaut), soit à la norme <i>l</i><sub>2</sub> (si <i>t</i> = 2), soit à la norme <i>l</i><sub>&infin;</sub> (si <i>t</i> = <tt>inf</tt>).</description>
    <description lang="de"></description>
    <description lang="es"></description>
    <description lang="el"></description>
    <description lang="zh"></description>
    <description lang="hr">Izračunava <i>l</i><sub>1</sub> ili <i>l</i><sub>2</sub> ili <i>l</i><sub>&infin;</sub> -normu matrice, ovisno o vrijednosti <i>t</i>: 1 (zadana vrijednost), 2 ili <tt>inf</tt>, redom.</description>
    <related>l1norm</related>
    <related>l2 norm</related>
    <related>linfnorm</related>
    <related>frobenius_norm</related>
    <example>matrix_norm([[1,2,3],[3,-9,6],[4,5,6]])</example>
    <example>matrix_norm([[1,2,3],[3,-9,6],[4,5,6]],1)</example>
    <example>matrix_norm([[1,2,3],[3,-9,6],[4,5,6]],2)</example>
    <example>matrix_norm([[1,2,3],[3,-9,6],[4,5,6]],inf)</example>
  </entry>
  <entry type="option">
    <name>fadeev</name>
    <category>Algebra:Linear</category>
    <description lang="en">Option of the <tt>pcar</tt> or <tt>charpoly</tt> command to specify the algorithm.</description>
    <description lang="fr">Option de la commande <tt>pcar</tt> ou <tt>charpoly</tt> pour spécifier l'algorithme utilisé.</description>
    <description lang="de"></description>
    <description lang="es">Opción del comando <tt>pcar</tt> o <tt>charpoly</tt> para especificar el algoritmo.</description>
    <description lang="el">Επιλογή της εντολής <tt>pcar</tt> ή <tt>charpoly</tt> για καθορισμό τον αλγόριθμο.</description>
    <description lang="zh"></description>
    <description lang="hr">Parametar za zadavanje algoritma prilikom upotrebe naredbi <tt>pcar</tt> i <tt>charpoly</tt>.</description>
    <related>pcar</related>
    <example>pcar([[4,1,-2],[1,2,-1],[2,1,0]],fadeev)</example>
  </entry>
  <entry type="command">
    <name>COND cond</name>
    <category>Algebra:Linear</category>
    <parameters ret="real">
      <mtrx/>
      <expr optional="true">t</expr>
    </parameters>
    <description lang="en">Condition number of a matrix, use <i>t</i> = 1 (the default) for <i>l</i><sub>1</sub> norm, <i>t</i> = 2 for <i>l</i><sub>2</sub> norm and <i>t</i> = <tt>inf</tt> for <i>l</i><sub>&infin;</sub> norm.</description>
    <description lang="fr">Nombre de condition d'une matrice: <i>t</i> = 1 (le défaut) pour la norme <i>l</i><sub>1</sub>, <i>t</i> = 2 pour la norme <i>l</i><sub>2</sub> et <i>t</i> = <tt>inf</tt> pour la norme <i>l</i><sub>&infin;</sub>.</description>
    <description lang="de"></description>
    <description lang="es"></description>
    <description lang="el"></description>
    <description lang="zh"></description>
    <description lang="hr">Broj uvjetovanosti matrice: za <i>t</i> = 1 (zadana vrijednost) koristi se <i>l</i><sub>1</sub>-norma, za <i>t</i> = 2 <i>l</i><sub>2</sub>-norma a za <i>t</i> = <tt>inf</tt> <i>l</i><sub>&infin;</sub>-norma.</description>
    <reference><a href="http://www.encyclopediaofmath.org/index.php?title=Condition_number">Condition number</a>. <i>Encyclopedia of Mathematics</i>.</reference>
    <related>SVL</related>
    <example>COND([[1,2],[1,4]])</example>
    <example>COND([[1,2],[1,4]],1)</example>
    <example>COND([[1,2],[1,4]],2)</example>
    <example>COND([[1,2],[1,4]],inf)</example>
  </entry>
  <entry type="command">
    <name>bezier</name>
    <category>Polynomials</category>
    <parameters ret="lst||geo2">
      <lst/>
      <option optional="true">plot</option>
    </parameters>
    <description lang="en">Bezier curve defined by control points (include the option <tt>plot</tt> to draw the curve).</description>
    <description lang="fr">Courbe de Bezier définie par des points de contrôle.</description>
    <description lang="de"></description>
    <description lang="es"></description>
    <description lang="el"></description>
    <description lang="zh"></description>
    <description lang="hr">Bezierova krivulja određena danim kontrolnim točkama (za prikaz krivulje treba navesti parametar <tt>plot</tt> kao drugi argument).</description>
    <reference><a href="http://www.encyclopediaofmath.org/index.php?title=Bezier_curve">Bezier curve</a>. <i>Encyclopedia of Mathematics</i>.</reference>
    <related>parameq</related>
    <example>bezier(1,1+i,2+i,3-i,plot)</example>
    <example>bezier(point([0,0,0]),point([1,1,0]),point([0,1,1]),plot)</example>
    <example>parameq(bezier(1,1+i,2+i,3-i))</example>
    <example>parameq(bezier(point([0,0,0]),point([1,1,0]),point([0,1,1])))</example>
  </entry>
  <entry type="command">
    <name>flatten</name>
    <category>General</category>
    <parameters ret="lst"><lst/></parameters>